//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YahtClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boat()
        {
            this.AccToBoats = new HashSet<AccToBoats>();
        }
    
        public int id { get; set; }
        public string model { get; set; }
        public int boat_type_id { get; set; }
        public string nummber_of_rowers { get; set; }
        public bool mast { get; set; }
        public int color_id { get; set; }
        public int wood_id { get; set; }
        public decimal base_price { get; set; }
        public string vat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccToBoats> AccToBoats { get; set; }
        public virtual BoatType BoatType { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Wood Wood { get; set; }
    }
}
