//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YahtClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string family_name { get; set; }
        public System.DateTime date_of_birthday { get; set; }
        public string adress { get; set; }
        public string city { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int pasport_id { get; set; }
        public int organisation_id { get; set; }
    
        public virtual Organisations Organisations { get; set; }
        public virtual Pasports Pasports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
