//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YahtClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int id { get; set; }
        public int contract_id { get; set; }
        public bool settled { get; set; }
        public decimal sum { get; set; }
        public decimal sum_inclVAT { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Contracts Contracts { get; set; }
    }
}
